/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceProductCategory = IDL.Variant({
  'consultingDevelopment' : IDL.Null,
  'contentMediaDesign' : IDL.Null,
  'others' : IDL.Null,
  'hardware' : IDL.Null,
  'hostingSupport' : IDL.Null,
});
export const VatCalculation = IDL.Record({
  'vatIdNumber' : IDL.Opt(IDL.Text),
  'toCountry' : IDL.Text,
  'priceGrossCents' : IDL.Nat,
  'category' : ServiceProductCategory,
  'fromCountry' : IDL.Text,
});
export const CalculationResult = IDL.Record({
  'exchangeRateAdjustment' : IDL.Float64,
  'priceNetEuros' : IDL.Float64,
  'priceGrossEuros' : IDL.Float64,
  'ifReverseChargeRequired' : IDL.Bool,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PdfFile = IDL.Record({
  'content' : IDL.Vec(IDL.Nat8),
  'filename' : IDL.Text,
});
export const ZipFile = IDL.Record({
  'content' : IDL.Vec(IDL.Nat8),
  'filename' : IDL.Text,
});
export const CsvFile = IDL.Record({
  'content' : IDL.Text,
  'filename' : IDL.Text,
});
export const ExcelFile = IDL.Record({
  'content' : IDL.Vec(IDL.Nat8),
  'filename' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PlanType = IDL.Variant({
  'pro' : IDL.Null,
  'starter' : IDL.Null,
  'free' : IDL.Null,
  'unsubscribed' : IDL.Null,
});
export const PlanUsage = IDL.Record({
  'plan' : PlanType,
  'monthlyInvoices' : IDL.Nat,
});
export const Time = IDL.Int;
export const EventRecord = IDL.Record({
  'id' : IDL.Text,
  'country' : IDL.Text,
  'metadata' : IDL.Text,
  'page' : IDL.Text,
  'device' : IDL.Text,
  'timestamp' : Time,
  'event_name' : IDL.Text,
});
export const InvoiceRecord = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'invoiceDate' : IDL.Text,
  'invoiceNumber' : IDL.Text,
  'htmlSource' : IDL.Text,
});
export const MappedPlanUsage = IDL.Record({
  'plan' : PlanType,
  'invoicesThisMonth' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculate' : IDL.Func([VatCalculation], [CalculationResult], []),
  'canICallApi' : IDL.Func([], [IDL.Text], ['query']),
  'canSaveInvoice' : IDL.Func([], [IDL.Bool], ['query']),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'downloadInvoiceAsPdf' : IDL.Func([IDL.Text], [PdfFile], []),
  'downloadInvoicesAsZip' : IDL.Func([IDL.Vec(IDL.Text)], [ZipFile], []),
  'downloadMonthInvoicesAsZip' : IDL.Func([IDL.Int, IDL.Nat], [ZipFile], []),
  'exportInvoicesAsCsv' : IDL.Func([], [CsvFile], []),
  'exportInvoicesAsExcel' : IDL.Func([], [ExcelFile], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentPlan' : IDL.Func([], [PlanType], ['query']),
  'getCurrentPlanUsage' : IDL.Func([], [PlanUsage], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(EventRecord)], ['query']),
  'getEventsByName' : IDL.Func([IDL.Text], [IDL.Vec(EventRecord)], ['query']),
  'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(InvoiceRecord)], ['query']),
  'getLastCalculation' : IDL.Func([], [IDL.Opt(VatCalculation)], ['query']),
  'getMappedPlanUsage' : IDL.Func([], [MappedPlanUsage], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUsage' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementUsage' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listInvoices' : IDL.Func([], [IDL.Vec(InvoiceRecord)], ['query']),
  'logEvent' : IDL.Func([EventRecord], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveInvoice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUserPlan' : IDL.Func([IDL.Principal, PlanType], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceProductCategory = IDL.Variant({
    'consultingDevelopment' : IDL.Null,
    'contentMediaDesign' : IDL.Null,
    'others' : IDL.Null,
    'hardware' : IDL.Null,
    'hostingSupport' : IDL.Null,
  });
  const VatCalculation = IDL.Record({
    'vatIdNumber' : IDL.Opt(IDL.Text),
    'toCountry' : IDL.Text,
    'priceGrossCents' : IDL.Nat,
    'category' : ServiceProductCategory,
    'fromCountry' : IDL.Text,
  });
  const CalculationResult = IDL.Record({
    'exchangeRateAdjustment' : IDL.Float64,
    'priceNetEuros' : IDL.Float64,
    'priceGrossEuros' : IDL.Float64,
    'ifReverseChargeRequired' : IDL.Bool,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PdfFile = IDL.Record({
    'content' : IDL.Vec(IDL.Nat8),
    'filename' : IDL.Text,
  });
  const ZipFile = IDL.Record({
    'content' : IDL.Vec(IDL.Nat8),
    'filename' : IDL.Text,
  });
  const CsvFile = IDL.Record({ 'content' : IDL.Text, 'filename' : IDL.Text });
  const ExcelFile = IDL.Record({
    'content' : IDL.Vec(IDL.Nat8),
    'filename' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PlanType = IDL.Variant({
    'pro' : IDL.Null,
    'starter' : IDL.Null,
    'free' : IDL.Null,
    'unsubscribed' : IDL.Null,
  });
  const PlanUsage = IDL.Record({
    'plan' : PlanType,
    'monthlyInvoices' : IDL.Nat,
  });
  const Time = IDL.Int;
  const EventRecord = IDL.Record({
    'id' : IDL.Text,
    'country' : IDL.Text,
    'metadata' : IDL.Text,
    'page' : IDL.Text,
    'device' : IDL.Text,
    'timestamp' : Time,
    'event_name' : IDL.Text,
  });
  const InvoiceRecord = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'invoiceDate' : IDL.Text,
    'invoiceNumber' : IDL.Text,
    'htmlSource' : IDL.Text,
  });
  const MappedPlanUsage = IDL.Record({
    'plan' : PlanType,
    'invoicesThisMonth' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculate' : IDL.Func([VatCalculation], [CalculationResult], []),
    'canICallApi' : IDL.Func([], [IDL.Text], ['query']),
    'canSaveInvoice' : IDL.Func([], [IDL.Bool], ['query']),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'downloadInvoiceAsPdf' : IDL.Func([IDL.Text], [PdfFile], []),
    'downloadInvoicesAsZip' : IDL.Func([IDL.Vec(IDL.Text)], [ZipFile], []),
    'downloadMonthInvoicesAsZip' : IDL.Func([IDL.Int, IDL.Nat], [ZipFile], []),
    'exportInvoicesAsCsv' : IDL.Func([], [CsvFile], []),
    'exportInvoicesAsExcel' : IDL.Func([], [ExcelFile], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentPlan' : IDL.Func([], [PlanType], ['query']),
    'getCurrentPlanUsage' : IDL.Func([], [PlanUsage], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(EventRecord)], ['query']),
    'getEventsByName' : IDL.Func([IDL.Text], [IDL.Vec(EventRecord)], ['query']),
    'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(InvoiceRecord)], ['query']),
    'getLastCalculation' : IDL.Func([], [IDL.Opt(VatCalculation)], ['query']),
    'getMappedPlanUsage' : IDL.Func([], [MappedPlanUsage], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUsage' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementUsage' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listInvoices' : IDL.Func([], [IDL.Vec(InvoiceRecord)], ['query']),
    'logEvent' : IDL.Func([EventRecord], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveInvoice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUserPlan' : IDL.Func([IDL.Principal, PlanType], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };